game:
  timer-seconds: 300
  powerup-cooldown-seconds: 30
  event-cooldown-seconds: 20
  item-give-interval-seconds: 3
  pillar-block-types:
    - BEDROCK
    - SAND
    - NETHERRACK
    - END_STONE
    - CHERRY_LOG
    - CRAFTING_TABLE
    - CHERRY_LEAVES
    - COBBLESTONE
    - OBSIDIAN
    - REDSTONE_BLOCK
    - TNT
    - NOTE_BLOCK
    - SEA_LANTERN
    - MELON
    - PUMPKIN
    - AMETHYST_BLOCK
    - GLASS
    - GLASS_PANE
  floor-block-types:
    - END_STONE
    - STONE
    - SLIME_BLOCK
    - AIR
    - HONEY_BLOCK
    - WHITE_WOOL
    - GLASS
    - GLASS_PANE
    - MOSS_BLOCK
    - CHERRY_LEAVES
    - NETHERRACK
    - BEDROCK
    - DIAMOND_BLOCK
    - COBWEB
    - CRAFTING_TABLE
    - SOUL_SAND
    - OAK_TRAPDOOR
    - MAGMA_BLOCK
    - TNT
    - BLACK_CARPET
    - BLUE_ICE
    - POINTED_DRIPSTONE
    - SCAFFOLDING
    - LAVA
    - WATER

