# ChaosPillars Configuration File
game:
  # Game timer in seconds must be atleast 180
  timer-seconds: 300

  # Powerup cooldown in seconds
  powerup-cooldown-seconds: 30

  # Event cooldown in seconds
  event-cooldown-seconds: 20

  # Item give interval in seconds
  item-give-interval-seconds: 3

  # Floor block types (must be valid Minecraft block names)
  floor-block-types:
    - END_STONE
    - STONE
    - SLIME_BLOCK
    - AIR
    - HONEY_BLOCK
    - WHITE_WOOL
    - GLASS
    - GLASS_PANE
    - MOSS_BLOCK
    - CHERRY_LEAVES
    - NETHERRACK
    - BEDROCK
    - DIAMOND_BLOCK
    - COBWEB
    - CRAFTING_TABLE
    - SOUL_SAND
    - OAK_TRAPDOOR
    - MAGMA_BLOCK
    - TNT
    - BLACK_CARPET
    - BLUE_ICE
    - POINTED_DRIPSTONE
    - SCAFFOLDING
    - LAVA
    - WATER

  # Pillar block types (must be valid Minecraft block names)
  pillar-block-types:
    - BEDROCK
    - SAND
    - NETHERRACK
    - END_STONE
    - CHERRY_LOG
    - CRAFTING_TABLE
    - CHERRY_LEAVES
    - COBBLESTONE
    - OBSIDIAN
    - REDSTONE_BLOCK
    - TNT
    - NOTE_BLOCK
    - SEA_LANTERN
    - MELON
    - PUMPKIN
    - AMETHYST_BLOCK
    - GLASS
    - GLASS_PANE
