game:
  timer-seconds: 300
  powerup-cooldown-seconds: 30
  event-cooldown-seconds: 20
  item-give-interval-seconds: 3
  pillar-block-types:
    - BEDROCK
    - SAND
    - NETHERRACK
    - END_STONE
    - OAK_LOG
    - CRAFTING_TABLE
    - IRON_BLOCK
    - OAK_LEAVES
    - COBBLESTONE
    - OBSIDIAN
    - GOLD_BLOCK
    - REDSTONE_BLOCK
    - EMERALD_BLOCK
    - TNT
    - NOTE_BLOCK
    - MOSSY_COBBLESTONE
    - PRISMARINE
    - HAY_BLOCK
    - MELON
    - PUMPKIN
    - MANGROVE_LOG
    - AMETHYST_BLOCK
  floor-block-types:
    - END_STONE
    - STONE
    - SLIME_BLOCK
    - AIR
    - HONEY_BLOCK
    - WHITE_WOOL
    - GLASS
    - GLASS_PANE
    - MOSS_BLOCK
    - GRASS_BLOCK
    - OAK_LOG
    - NETHERRACK
    - BEDROCK
    - COBWEB
    - CRAFTING_TABLE
    - SOUL_SAND
    - OAK_TRAPDOOR
    - MAGMA_BLOCK
    - ICE
    - TNT
    - BLACK_CARPET
    - BLUE_ICE
    - POINTED_DRIPSTONE
    - SCAFFOLDING
    - LAVA
    - WATER

