game:
  world-name: "world"
  timer-seconds: 300
  powerup-cooldown-seconds: 30
  event-cooldown-seconds: 20
  item-give-interval-seconds: 3
  pillar-block-types:
    - BEDROCK
    - SAND
    - NETHERRACK
    - END_STONE
    - OAK_LOG
    - CRAFTING_TABLE
    - IRON_BLOCK
    - OAK_LEAVES
    - COBBLESTONE
    - OBSIDIAN
    - GOLD_BLOCK
    - REDSTONE_BLOCK
    - EMERALD_BLOCK
    - TNT
    - NOTE_BLOCK
    - MOSSY_COBBLESTONE
    - PRISMARINE
    - HAY_BLOCK
    - MELON
    - PUMPKIN
    - MANGROVE_LOG
    - AMETHYST_BLOCK
  floor-block-types:
    - END_STONE
    - SLIME_BLOCK
    - AIR
    - HONEY_BLOCK
    - GRASS_BLOCK
    - OAK_LOG
    - NETHERRACK
    - BEDROCK
    - DIAMOND_BLOCK
    - COBWEB
    - CRAFTING_TABLE
    - SOUL_SAND
    - MAGMA_BLOCK
    - ICE
    - PACKED_ICE
    - BLUE_ICE
    - DRIPSTONE_BLOCK
    - SCAFFOLDING
    - LAVA
    - WATER
    - GLOWSTONE
    - SEA_LANTERN
    - TERRACOTTA
    - SHROOMLIGHT
    - WARPED_NYLIUM
    - CRYING_OBSIDIAN

