game:
  world-name: "world"
  timer-seconds: 300
  powerup-cooldown-seconds: 30
  event-cooldown-seconds: 20
  item-give-interval-seconds: 3
  pillar-block-types:
    - BEDROCK
    - SAND
    - NETHERRACK
    - END_STONE
    - OAK_LOG
  floor-block-types:
    - END_STONE
    - SLIME_BLOCK
    - AIR
    - HONEY_BLOCK
    - GRASS_BLOCK
    - OAK_LOG
    - NETHERRACK
    - BEDROCK
    - DIAMOND_BLOCK
    - COBWEB
