name: ChaosPillars
main: com.boes.chaospillars.ChaosPillars
version: 1.7
api-version: 1.20
commands:
  chaos:
    description: Root command for Chaos Pillars
    usage: /<command> <start|stop|reload|stats>
    permission: chaospillars.use
  ChaosDebug:
    description: Spawns a fake player for testing
    usage: /ChaosDebug
    permission: op
permissions:
  chaospillars.use:
    description: Use the base /chaos command
    default: true

  chaospillars.start:
    description: Start the Chaos Pillars game
    default: true

  chaospillars.stop:
    description: Stop the Chaos Pillars game
    default: op

  chaospillars.reload:
    description: Reload Chaos Pillars config
    default: op

worlds:
  Chaospillars:
    generator: com.boes.chaospillars.tasks.SetupTask$VoidGenerator
