name: ChaosPillars
main: com.boes.chaospillars.ChaosPillars
version: 1.8.0
api-version: 1.21
commands:
  chaos:
    description: Root command for Chaos Pillars
    usage: /<command> <start|stop|reload|stats|secondring|configlist>
    permission: chaospillars.use
permissions:
  chaospillars.use:
    description: Use the base /chaos command
    default: true

  chaospillars.start:
    description: Start the Chaos Pillars game
    default: true

  chaospillars.stop:
    description: Stop the Chaos Pillars game
    default: op

  chaospillars.reload:
    description: Reload Chaos Pillars config
    default: op

  chaospillars.admin:
    description: Admin commands for Chaos Pillars
    default: op

