name: ChaosPillars
main: com.boes.chaospillars.ChaosPillars
version: 1.0
api-version: 1.20
commands:
  startchaos:
    description: Starts the Chaos Pillars game
  stopchaos:
    description: Stops the Chaos Pillars game
